import type { CreditProfile } from "./types";
import { normalizePin } from "@/lib/account/store";

const history = (end: number, start: number): CreditProfile["history"] => {
  const months = ["2025-10-01", "2025-11-01", "2025-12-01", "2026-01-01", "2026-02-01", "2026-03-01", "2026-04-01", "2026-05-01", "2026-06-01", "2026-07-01", "2026-08-01", "2026-09-01"];
  return months.map((date, i) => ({
    date,
    score: Math.round(start + ((end - start) * i) / (months.length - 1)),
  }));
};

export const PROFILES: CreditProfile[] = [
  {
    id: "ama",
    name: "Ama Serwaa",
    label: "Good · 687",
    score: 687,
    previousScore: 679,
    updatedLabel: "Pulled today",
    onTimeRate: 0.98,
    ageMonths: 76,
    inquiries24mo: 2,
    cheques: 0,
    judgments: 0,
    socio: "Salaried · Accra",
    assets: "Steady salary, modest card room",
    bureaus: { xds: 678, dnb: 684, mcs: 699 },
    history: history(687, 641),
    accounts: [
      {
        id: "fido",
        name: "Fido",
        kind: "Digital loan",
        type: "revolving",
        balance: 1350,
        limit: 1500,
        opened: "2024-03-12",
        lastReported: "Last reported one month ago",
        paymentStatus: "current",
        status: "open",
      },
      {
        id: "eco",
        name: "Ecobank",
        kind: "Visa card",
        type: "revolving",
        balance: 1840,
        limit: 8000,
        opened: "2019-08-04",
        lastReported: "Last reported one month ago",
        paymentStatus: "current",
        status: "open",
      },
      {
        id: "absa",
        name: "Absa",
        kind: "Credit card",
        type: "revolving",
        balance: 400,
        limit: 4000,
        opened: "2021-11-18",
        lastReported: "Last reported one month ago",
        paymentStatus: "current",
        status: "open",
      },
      {
        id: "cal",
        name: "CalBank",
        kind: "Salary loan",
        type: "installment",
        balance: 8200,
        original: 18000,
        opened: "2023-06-01",
        lastReported: "Last reported 18 days ago",
        paymentStatus: "current",
        status: "open",
      },
      {
        id: "sltf",
        name: "Student Loan Trust",
        kind: "Student loan",
        type: "installment",
        balance: 5400,
        original: 9000,
        opened: "2018-09-01",
        lastReported: "Last reported one month ago",
        paymentStatus: "current",
        status: "open",
      },
    ],
  },
  {
    id: "akosua",
    name: "Akosua Mensah",
    label: "Excellent · 742",
    score: 742,
    previousScore: 736,
    updatedLabel: "Pulled today",
    onTimeRate: 1,
    ageMonths: 128,
    inquiries24mo: 1,
    cheques: 0,
    judgments: 0,
    socio: "Salaried · East Legon",
    assets: "Home loan in good standing",
    bureaus: { xds: 736, dnb: 744, mcs: 748 },
    history: history(742, 711),
    accounts: [
      {
        id: "stanbic",
        name: "Stanbic",
        kind: "Visa card",
        type: "revolving",
        balance: 420,
        limit: 12000,
        opened: "2016-04-22",
        lastReported: "Last reported 12 days ago",
        paymentStatus: "current",
        status: "open",
      },
      {
        id: "absa2",
        name: "Absa",
        kind: "Credit card",
        type: "revolving",
        balance: 200,
        limit: 15000,
        opened: "2018-01-09",
        lastReported: "Last reported one month ago",
        paymentStatus: "current",
        status: "open",
      },
      {
        id: "access",
        name: "Access Bank",
        kind: "Credit card",
        type: "revolving",
        balance: 0,
        limit: 8000,
        opened: "2020-06-15",
        lastReported: "Last reported 9 days ago",
        paymentStatus: "current",
        status: "open",
      },
      {
        id: "home",
        name: "Republic Bank",
        kind: "Home loan",
        type: "installment",
        balance: 180000,
        original: 240000,
        opened: "2021-02-01",
        lastReported: "Last reported one month ago",
        paymentStatus: "current",
        status: "open",
      },
    ],
  },
  {
    id: "kwame",
    name: "Kwame Boateng",
    label: "Below average · 578",
    score: 578,
    previousScore: 591,
    updatedLabel: "Pulled today",
    onTimeRate: 0.86,
    ageMonths: 28,
    inquiries24mo: 6,
    cheques: 2,
    judgments: 1,
    socio: "Self-employed · Kumasi",
    assets: "Thin file, high balances",
    bureaus: { xds: 560, dnb: 571, mcs: 590 },
    history: history(578, 612),
    accounts: [
      {
        id: "bayport",
        name: "Bayport",
        kind: "Payroll loan",
        type: "revolving",
        balance: 2100,
        limit: 2500,
        opened: "2024-02-11",
        lastReported: "Last reported 8 days ago",
        paymentStatus: "late30",
        status: "open",
      },
      {
        id: "letshego",
        name: "Letshego",
        kind: "Personal loan",
        type: "revolving",
        balance: 890,
        limit: 1000,
        opened: "2025-01-20",
        lastReported: "Last reported one month ago",
        paymentStatus: "current",
        status: "open",
      },
      {
        id: "quick",
        name: "Quick Credit",
        kind: "Installment loan",
        type: "installment",
        balance: 640,
        original: 1800,
        opened: "2025-05-03",
        lastReported: "Last reported 21 days ago",
        paymentStatus: "late30",
        status: "open",
      },
      {
        id: "gcb",
        name: "GCB Bank",
        kind: "Auto loan",
        type: "installment",
        balance: 18600,
        original: 21400,
        opened: "2024-09-14",
        lastReported: "Last reported one month ago",
        paymentStatus: "current",
        status: "open",
      },
    ],
  },
];

export const DEFAULT_PROFILE_ID = "ama";

const PIN_FILE: Record<string, string> = {
  "GHA-723188461-5": "ama",
  "GHA-110294883-2": "kwame",
  "GHA-880441227-9": "akosua",
};

export const DEMO_PINS = [
  { pin: "GHA-723188461-5", name: "Ama Serwaa", label: "Good" },
  { pin: "GHA-110294883-2", name: "Kwame Boateng", label: "Below average" },
  { pin: "GHA-880441227-9", name: "Akosua Mensah", label: "Excellent" },
] as const;

export function profileForPin(pin?: string | null) {
  const key = normalizePin(pin ?? "");
  const id = PIN_FILE[key];
  if (id) return PROFILES.find((p) => p.id === id) ?? PROFILES[0];
  if (!key) return PROFILES[0];
  const n = key.replace(/\D/g, "").split("").reduce((sum, d) => sum + Number(d), 0);
  return PROFILES[n % PROFILES.length];
}